#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# "Alias like" functions to simplify common operations:
function extract(){
	# Extract eiter a tar or zip file
	[ $# -eq 1 ] && tar -xzvf $1  2>/dev/null || unzip $1
	[ $# -eq 2 ] && tar -xzvf $1 $2 || unzip $1 $2
}
function compress(){
	# Compress using pigz for multi-thread optimization
	out=$1; shift
	tar --use-compress-program=pigz -cvf $out $@
}
function cmpt(){
	# "comparison test": evaluate a bash expression as True or False
	eval $1 && echo "True" && return
	eval $1 || echo "False" && return
}
function ccat(){
	# "Color Cat"
	highlight --out-format=ansi  $1 || highlight --out-format=ansi --syntax=bash $1
}
function refresh(){
	# Clear terminal
	[[ "$1" = "-c" ]] && shift && clear
	# load any edits to shell configuration, environment, or scripts
	unalias -a
	shortcuts >/dev/null
	source ~/.zprofile
	source ~/.zshrc
	# Add permission execution to all bin scripts specified
	if [[ "$1" = "-x" ]]; then
		shift
		pushd ~/.local/bin &> /dev/null
		sudo chmod +x $(realpath $@)
		popd &> /dev/null
	fi
}

# Alias functions
alias \
	x="extract" \
	c="compress" \
	rf="refresh" \
	rfc="refresh -c" \
	rfx="refresh -x" \


# Aliases I am used to using
alias \
	nv="nvim" \
	spm="pacman" \
	cl="clear" \

# Use list deluxe and alias useful list options
alias \
	ls="lsd --group-dirs first" \
	la="ls -lA" \
	las="ls -lAs" \
	ltr="ls -lAtr" \
	lt="ls --tree" \
	lta="lt -lA" \

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	dd="sudo dd bs=256k status=progress conv=noerror,sync" \

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \



# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
	v="VBoxManage" \
	vs="VBoxManage startvm" \
	iptraf="sudo iptraf-ng" \


alias \
	magit="nvim -c MagitOnly" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
