#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Change this for your monitor setup
xrandr --output DP-2 --mode 2560x1440 --refresh 143.91 --primary
xrandr --output DP-0 --mode 2560x1440 --rotate right --right-of DP-2

setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	xrdbpid=$!
remaps &		# run the remaps script, switching caps/esc and more; check it for more info

autostart="mpd xcompmgr dunst unclutter"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.

pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

export QT_STYLE_OVERRIDE="Adwaita-Dark"

# Wait for xrdb merge to finish before init
[ -n "$xrdbpid" ] && wait "$xrdbpid"
